spring.datasource.url=jdbc:postgresql://dpg-d7b6v98ule4c738sp9e0-a:5432/iot_db_veg6
spring.datasource.username=iotdb_gz1n_user
spring.datasource.password=iVuN78UhB0AwMGhhajDTrczGgZBB66J4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true