spring.application.name=homeautomation

spring.datasource.url=jdbc:postgresql://dpg-d7b6v98ule4c738sp9e0-a.oregon-postgres.render.com:5432/iot_db_veg6
spring.datasource.username=iot_db_veg6_user
spring.datasource.password=jjCSOM6S9xQIMRT8HrmVbXBQ3glEMFmf

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true